# Connection keep alive timeout [default: 75]
keep_alive: 75
# Number of web server workers
worker_processes: 8
# Amount of memory (in MB) to use for caching tiles [default: 512, 0 to disable]
cache_size_mb: 1024
watch: true

postgres:
  connection_string: '{$REMOTE_INSPIRE_URL}'
  default_srid: 4326
  pool_size: 20
  max_feature_count: null # either a positive integer, or null=unlimited (default)
  auto_bounds: calc
  # Enable automatic discovery of tables and functions.
  # You may set this to `false` to disable.
  auto_publish:
    # Optionally limit to just these schemas
    from_schemas:
      - inspire






