cache_size_mb: 1024
keep_alive: 100
postgres:
  default_srid: 4326
  auto_bounds: calc
  pool_size: 50
  auto_publish: true
  tables:
    mv_cadastralparcel_4326:
      schema: inspire       
      table: mv_cadastralparcel_4326
      srid: 4326            
      geometry_column: geometry
      bounds:               
      - -9.499050804036969  
      - 36.99350227610016   
      - -6.419221510790907  
      - 41.46712859139252   
      geometry_type: GEOMETRY
      properties:           
        administrativeunit: varchar
        areavalue: float8   
        beginlifespanversion: timestamptz
        endlifespanversion: timestamptz
        id: int4            
        inspireid: text     
        label: varchar      
        nationalcadastralreference: varchar
        validfrom: timestamptz
        validto: timestamptz 
  functions: {}              
