# =================================================================
#
# Authors: doublebyte1 <jo@byteroad.net>>
#
# Copyright (c) 2024 doublebyte
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

services:

  apache-httpd:
    image: httpd:2.4
    container_name: httpd
    depends_on:
      - pygeoapi
    volumes:
      - ./apache-httpd/httpd-ssl.conf:/usr/local/apache2/conf/httpd.conf      
      # - /etc/cert/ogcapi_chain.cer:/usr/local/apache2/conf/ogcapi/fullchain.pem
      # - /etc/cert/ogcapi_privkey.pem:/usr/local/apache2/conf/ogcapi/privkey.pem
      # - /etc/cert/logs_chain.cer:/usr/local/apache2/conf/matomo/fullchain.pem
      # - /etc/cert/logs_privkey.pem:/usr/local/apache2/conf/matomo/privkey.pem
      - /etc/cert/logs_privkey.pem:/usr/local/apache2/conf/ogcapi/privkey.pem
      - /etc/cert/logs.jks:/usr/local/apache2/conf/ogcapi/keystore.jks    
      - /etc/cert/logs_chain.cer:/usr/local/apache2/conf/ogcapi/chain.cer
      - /etc/cert/logs_privkey.pem:/usr/local/apache2/conf/matomo/privkey.pem
      - /etc/cert/logs.jks:/usr/local/apache2/conf/matomo/keystore.jks    
      - /etc/cert/logs_chain.cer:/usr/local/apache2/conf/matomo/chain.cer
      - apache_log:/usr/local/apache2/logs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default

  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi
    expose:
      - "80"
    environment:
      PYGEOAPI_CONFIG: docker-config.yml
      PYGEOAPI_OPENAPI: example-openapi.yml
    env_file:
      - .env     # path to your .env file
    volumes:
      - ./pygeoapi/docker.config.yml:/pygeoapi/local.config.yml
      - ./data:/data
    restart: on-failure
    links:
      - tiles
    networks:
      - default
    depends_on:
      db_and_api_init:
        condition: service_completed_successfully
        restart: true

  tiles:
    image: ghcr.io/maplibre/martin
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgis
    networks:
      - default

  postgis:
    build: ./postgis/
    environment:
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env     # path to your .env file
    expose:
       - 5432
    ports:
      - "5432:5432"
    container_name: postgis
    volumes:
       - ./postgis/data:/var/lib/postgresql/data
       - ./postgis/scripts:/tmp/
    networks:
      - default
      - bridge1

  db_and_api_init:
    build: ./utils/
    container_name: db_and_api_init
    env_file:
      - .env     # path to your .env file
    volumes:
      - ./pygeoapi/docker.config.yml:/pygeoapi/docker.config.yml
      - ./data:/data
    depends_on:
      - postgis
    networks:
      - default

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - maria:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - .env
    networks:
      - default

  matomo:
    build:
      context: ./matomo/
      dockerfile: Dockerfile.main
    container_name: matomo
    ports:
      - 8081:80
    volumes:
      - matomo:/var/www/html:z
      - apache_log:/apache:ro
    environment:
      - MATOMO_DATABASE_HOST=mariadb
    env_file:
      - .env
    networks:
      - default

  python_matomo:
    build:
      context: ./matomo/
      dockerfile: Dockerfile.cron
    container_name: matomo_python
    volumes:
        - matomo:/var/www/html:z
        - apache_log:/apache:ro
    depends_on:
      - matomo
  



volumes:
  maria:
  matomo:
  apache_log:

networks:
  default:
  bridge1: