# =================================================================
#
# Authors: doublebyte1 <jo@byteroad.net>>
#
# Copyright (c) 2024 doublebyte
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

services:

  apache-httpd:
    image: httpd:2.4
    container_name: httpd
    depends_on:
      - pygeoapi
    volumes:
      - ./apache-httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 4G

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/config/logstash.conf
    ports:
      - "5000:5000"
    command: logstash -f /usr/share/logstash/config/logstash.conf
    networks:
      - default

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - default

  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi
    expose:
      - "80"
    environment:
      PYGEOAPI_CONFIG: docker-config.yml
      PYGEOAPI_OPENAPI: example-openapi.yml
    env_file:
      - .env     # path to your .env file
    volumes:
      - ./pygeoapi/docker.config.yml:/pygeoapi/local.config.yml
    restart: on-failure
    links:
      - tiles
    networks:
      - default

  tiles:
    image: ghcr.io/maplibre/martin
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgis
    networks:
      - default

  postgis:
    build: ./postgis/
    environment:
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env     # path to your .env file
    expose:
       - 5432
    ports:
      - "5432:5432"
    container_name: postgis
    volumes:
       - ./postgis/data:/var/lib/postgresql/data
    networks:
      - default
      - bridge1

networks:
  default:
  bridge1: