server:
  bind:
    host: 0.0.0.0:80
    port: 80
  url: http://localhost:80/
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
  - en-US
  - fr-CA
  cors: true
  pretty_print: true
  limit: 1000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap
      contributors</a>'
logging:
  level: DEBUG
  logfile: /tmp/pygeoapi.log
metadata:
  identification:
    title:
      en: pygeoapi default instance
      fr: instance par défaut de pygeoapi
    description:
      en: pygeoapi provides an API to geospatial data
      fr: pygeoapi fournit une API aux données géospatiales
    keywords:
      en:
      - geospatial
      - data
      - api
      fr:
      - géospatiale
      - données
      - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://example.org
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Organization Name
    url: https://pygeoapi.io
  contact:
    name: Lastname, Firstname
    position: Position Title
    address: Mailing Address
    city: City
    stateorprovince: Administrative Area
    postalcode: Zip or Postal Code
    country: Country
    phone: +xx-xxx-xxx-xxxx
    fax: +xx-xxx-xxx-xxxx
    email: you@example.org
    url: Contact URL
    hours: Mo-Fr 08:00-17:00
    instructions: During hours of service. Off on weekends.
    role: pointOfContact
resources:
  crus:
    description: Carta do Regime de Uso do Solo
    extents:
      spatial:
        bbox:
        - -9.52657060387
        - 36.838268541
        - -6.3890876937
        - 42.280468655
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: 2000-10-30 18:24:39+00:00
        end: 2007-10-30 08:57:29+00:00
    keywords:
    - Uso do Solo
    - Portugaç
    - CRUS
    links:
    - href: https://snig.dgterritorio.gov.pt/rndg/srv/por/catalog.search#/metadata/517c5023-04cc-47a4-99f7-bb32814dd62f
      hreflang: en-US
      rel: canonical
      title: data
      type: text/csv
    providers:
    - data:
        dbname: geodb
        host: postgis
        user: ${POSTGRES_USER}
      geom_field: geometry
      id_field: objectid
      name: PostgreSQL
      search_path:
      - geostore
      - public
      table: crus
      type: feature
    - data: http://tiles:3000/crus/{z}/{x}/{y}?f=mvt
      format:
        mimetype: application/vnd.mapbox-vector-tile
        name: pbf
      name: MVT-proxy
      options:
        schemes:
        - WebMercatorQuad
        zoom:
          max: 15
          min: 0
      type: tile
    title: CRUS
    type: collection